### ISSUE TITLE
Allow BitBucket commits as well

### ISSUE THREAD

**Issue by webknjaz** [100DaysOfCommits/100DaysOfCommits.github.io#1]
Hi @thejessleigh,

I think someone would prefer BitBucket over GitHub. Perhaps this should be outlined somewhere?

**Comment by thejessleigh** [comment]
That's a good point. I'm less familiar with BitBucket and Mercurial myself. I'll look at adding in some language about it this weekend. Thanks for pointing this out.

**Comment by webknjaz** [comment]
You are welcome :) 
BTW Bitbucket supports both git and mercurial

**Comment by thejessleigh** [comment]
@webknjaz I added a little bit of language to the FAQ about bitbucket, gitlab. I'll try to put some beginner resources on the resources page in the next few days. Let me know if you think I missed any important information. https://github.com/100DaysOfCommits/100DaysOfCommits.github.io/commit/3177cbac485206638e9f36c53eedb5e4cae84b36

**Comment by webknjaz** [comment]
Sure thanks :)

**Comment by webknjaz** [comment]
@thejessleigh I think, it's important to highlight start/end timezone (end exact time as well)

**Comment by thejessleigh** [comment]
Added some additional language around bitbucket to overview page af9fb15e01c6a868b91232a5be029708a586dcd1.
