### ISSUE TITLE
Add social media buttons to footer 

### ISSUE THREAD

**Issue by thejessleigh** [100DaysOfCommits/100DaysOfCommits.github.io#5]
Or maybe header? Haven't decided yet.

Should include
twitter (https://www.twitter.com/100Commits)
facebook (https://www.facebook.com/100daysofcommits/)
instagram (https://www.instagram.com/100daysofcommits/)

**Comment by KaraAJC** [comment]
OOH I can do this!
![bitmoji](https://render.bitstrips.com/v2/cpanel/10134275-11800032_1-s1-v1.png?transparent=1&width=246)

**Comment by thejessleigh** [comment]
Go for it! :)

**Comment by thejessleigh** [comment]
Close with pull request https://github.com/100DaysOfCommits/100DaysOfCommits.github.io/pull/8

**Comment by KaraAJC** [comment]
@![bitmoji](https://render.bitstrips.com/v2/cpanel/10134278-11800032_1-s1-v1.png?transparent=1&width=246)
