### ISSUE TITLE
Adjust styling to match logo. Add logo to header.

### ISSUE THREAD

**Issue by thejessleigh** [100DaysOfCommits/100DaysOfCommits.github.io#6]

**Comment by thejessleigh** [comment]
I have resource files for this. If a non-me person would like to take this on, please let me know.

**Comment by KaraAJC** [comment]
I'm gonna try this out, anyone wanna pair with me on this??

**Comment by thejessleigh** [comment]
@KaraAJC if you need any support from me, let me know. I will put the logo resource files up in the `images` directory later today.

**Comment by thejessleigh** [comment]
@KaraAJC logo png and svg files were added in https://github.com/100DaysOfCommits/100DaysOfCommits.github.io/commit/eab87bc457db281625ec992179d14cf3b88d9a0d

Let me know if you need any more information of if there's anything I can do to help.
